---
exclude: ['Gemfile', 'Gemfile.lock', 'README.markdown']
markdown: 'redcarpet'
redcarpet:
  extensions: ['no_intra_emphasis', 'tables']
permalink: pretty
pygments: true
safe: false
host: tatey.com
